import { Experience, OrganizationExperience, Project, Certificate, SkillGroup } from '@/types/portfolio'

export const navItems = [
  { label: 'About', href: '/about' },
  { label: 'Experience', href: '/experience' },
  { label: 'Projects', href: '/projects' },
  { label: 'Certificates', href: '/certificates' },
  { label: 'Contact', href: '/contact' },
]

export const skillGroups: SkillGroup[] = [
  { title: 'Data & Database', label: 'DATABASE', items: ['SQL', 'SQL Server', 'Oracle', 'Database Systems', 'Excel', 'Data Cleaning'] },
  { title: 'Data Analysis & Machine Learning', label: 'DATA & ML', items: ['Python', 'Pandas', 'NumPy', 'Exploratory Data Analysis (EDA)'] },
  { title: 'Deep Learning', label: 'AI & DL', items: ['TensorFlow', 'Keras', 'Transfer Learning'] },
  { title: 'Web Development', label: 'FULLSTACK', items: ['React', 'Node.js', 'Laravel', 'Blade', 'PHP', 'HTML', 'CSS', 'MySQL'] },
  { title: 'Tools & Workflow', label: 'WORKFLOW', items: ['Git', 'Jupyter Notebook', 'VS Code'] },
  { title: 'Tools', label: 'ECOSYSTEM', items: ['GitHub', 'Visual Studio Code'] },
]

export const experiences: Experience[] = [
  {
    company: 'VINIX7 – Internship Program',
    role: 'Data Analyst Division',
    period: 'Feb 2026 – Jun 2026',
    highlights: [
      'Built a Tableau dashboard using 5,525 patient visits across 5 polyclinics to track waiting times, payment methods, and patient demographics.',
      'Analyzed 1,524 cases with 60+ minute waiting times, finding longer waits among elderly BPJS patients visiting in the morning with 389 visits averaging 74.4 minutes.',
      'Analyzed 187 hotel customer reviews to find common service issues and rating patterns for improvement recommendations.',
    ],
    tags: ['Excel', 'Spreadsheet', 'Tableau'],
  },
]

export const organizationExperiences: OrganizationExperience[] = [
  {
    organization: 'SNAP Photography Universitas Gunadarma – Depok, Indonesia',
    role: 'Staff Of External Public Relations Division',
    period: 'Sep 2023 – Aug 2024',
    description: 'Organisational Internal Campus',
    highlights: [
      'Coordinated and managed organization events, including meetings, workshops, and promotional activities, to keep participation and support consistent.',
      'Built partnerships with SMEs and other campus organizations to support collaboration.',
      "Proposed and helped run creative initiatives, such as visual campaigns and collaborative projects, to strengthen the organization's appeal.",
    ],
  },
  {
    organization: 'Exhibition Bhavadarshana – Depok, Indonesia',
    role: 'Head Of Sponsorship Division',
    period: 'Dec 2023 – Mar 2024',
    description: 'Photography Exhibition Event',
    highlights: [
      'Led sponsorship acquisition researched and approached potential partners, negotiated agreements, and managed sponsor relationships across event media and communication channels.',
      'Secured 5 key sponsors, 3 media supports, and 14 media partners, contributing to event funding and brand visibility.',
    ],
  },
  {
    organization: 'Seminar Photography – Depok, Indonesia',
    role: 'Coordinator of Event & MC',
    period: 'March 2023',
    description: 'A Forum for Developing the Skills and Knowledge of Photography Professionals',
    highlights: [
      'Led event planning by developing the concept, theme, and overall rundown.',
      'Coordinated team responsibilities and cross-division execution.',
      'Served as Master of Ceremony, leading the event flow and engaging participants.',
      'Drew an audience of 54 participants.',
    ],
  },
  {
    organization: 'Exhibition Awal Karya – Jakarta, Indonesia',
    role: 'Head Of Event Division',
    period: 'Feb 2023 – Mar 2023',
    description: 'Photography Exhibition Event',
    highlights: [
      'Responsible for conceptualizing, theme development, and overall execution of the event.',
      'Defined team responsibilities and coordinated cross division efforts to ensure smooth event execution.',
      'Drew an audience of 648 people.',
    ],
  },
]

export const projects: Project[] = [
  {
    id: 'academy-next-top-model',
    title: 'Academy Next Top Model Website',
    tagline: 'Jul 2026 – Aug 2026',
    category: 'Freelance Project | Web Developer',
    highlights: [
      'Maintained and improved the Laravel-based Academy Next Top website for a freelance client.',
      'Developed a hybrid AI chatbot using Flask with static FAQ handling, MySQL-based dynamic queries, multi-intent detection, and context-aware responses.',
      'Built admin dashboard features for managing chatbot data and configurations, with sensitive topics redirected to WhatsApp.',
      'Achieved 88.89% test accuracy and 87.50% average accuracy across evaluations.',
    ],
    tags: ['Laravel', 'PHP', 'Flask', 'Python', 'MySQL'],
    githubUrl: 'https://github.com/Farchairul/academyntm',
    previewVideoUrl: 'https://github.com/Farchairul/portfolio/releases/download/v1.0.0-previews/Preview_Academy._Next_Top_Model.mp4',
  },
  {
    id: 'umkm-laundry-website',
    title: 'UMKM Laundry Website',
    tagline: 'Oct 2025 – Dec 2025',
    category: 'Community Service Project | Project Manager',
    highlights: [
      'Managed project planning, task allocation, and development progress for a laundry business website.',
      'Designed the UI and page layouts for the company profile and laundry service pages using Figma.',
      'Developed service management features for customer records, transactions, and daily workflows using Laravel, Blade, and MySQL.',
    ],
    tags: ['Laravel', 'Blade', 'MySQL', 'Figma'],
    githubUrl: 'https://github.com/Farchairul/umkmlaundry',
    previewVideoUrl: 'https://github.com/Farchairul/portfolio/releases/download/v1.0.0-previews/Preview_Web_UMKM_Laundry.mp4',
  },
  {
    id: 'explainable-ecg-diagnosis',
    title: 'Explainable ECG Diagnosis Web App',
    tagline: 'Feb 2026 – Apr 2026',
    category: 'Thesis Project (Skripsi) | Individual | Gunadarma University',
    highlights: [
      'Built a full-stack ECG analysis web app using CNN-BiLSTM-Attention for 3-class cardiac disease classification, achieving 85.16% accuracy and 82.57% F1-score.',
      'Developed a FastAPI-based pipeline supporting npy, npz, and WFDB ECG uploads with integrated preprocessing and model inference connected to a React frontend.',
      'Implemented Grad-CAM explainability to visualize model decision regions and designed a React interface for ECG upload, results, and interpretation.',
    ],
    tags: ['React (Vite)', 'FastAPI', 'Python', 'CNN-BiLSTM-Attention', 'Grad-CAM'],
    liveUrl: 'https://farchairul-cardioxplain.hf.space/',
    githubUrl: 'https://github.com/Farchairul/cardioxplain',
  },
  {
    id: 'rice-leaf-disease-detection',
    title: 'Rice Leaf Disease Detection Website',
    tagline: 'Freelance Project',
    category: 'Freelance Project | Web Developer',
    highlights: [
      'Developed a responsive web application integrating a pre-trained CNN/VGG16 model for rice leaf disease detection, with image upload, diagnosis results, and Grad-CAM heatmap visualization.',
      'Built a disease reference covering 8 classes and optimized the prediction workflow to deliver results in under 3 seconds.',
    ],
    tags: ['React', 'Vite', 'Tailwind CSS', 'Framer Motion'],
    githubUrl: 'https://github.com/Farchairul/oryzadetect',
    previewVideoUrl: 'https://github.com/Farchairul/portfolio/releases/download/v1.0.0-previews/Preview_OryzaDetect.mp4',
  },
  {
    id: 'wayang-classification',
    title: 'Wayang Classification',
    tagline: 'Feb 2026',
    category: 'AI Project | Deep Learning & Web',
    highlights: [
      'Developed an AI-powered image classification application using EfficientNet.',
      'Integrated the deep learning model into a React & Flask full-stack application.',
      'Implemented image prediction with confidence scores for user-facing results.',
    ],
    tags: ['Python', 'TensorFlow', 'Keras', 'EfficientNet', 'Flask', 'React', 'TypeScript', 'Tailwind CSS'],
    githubUrl: 'https://github.com/Farchairul/klasifikasi-wayang',
    previewVideoUrl: 'https://github.com/Farchairul/portfolio/releases/download/v1.0.0-previews/Preview_Klasifikasi_Wayang.mp4',
  },
  {
    id: 'skin-disease-classification',
    title: 'Skin Disease Classification',
    tagline: 'Jun 2025 – Aug 2025',
    category: 'Machine Learning & Healthcare | Researcher',
    highlights: [
      'Developed a skin disease image classification model using transfer learning.',
      'Compared VGG16 and EfficientNetB0 through model evaluation and fine-tuning.',
      'Achieved 96.58% accuracy with VGG16 on the evaluation dataset.',
    ],
    tags: ['Python', 'TensorFlow', 'Keras', 'VGG16', 'EfficientNetB0', 'Jupyter Notebook'],
    githubUrl: 'https://github.com/Farchairul/skin-disease-classification',
  },
  {
    id: 'taktik-bola',
    title: 'TaktikBola',
    tagline: 'May 2026 – Jun 2026',
    category: 'Interactive Web Platform | Frontend Engineer',
    highlights: [
      'Developed an interactive football learning platform for tactical education.',
      'Designed interactive drag-and-drop tactical learning experiences.',
      'Implemented animations and data visualization to enhance the learning experience.',
    ],
    tags: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Three.js', 'GSAP', 'Framer Motion', 'Recharts', 'Dnd Kit'],
    githubUrl: 'https://github.com/Farchairul/taktikbola',
    previewVideoUrl: 'https://github.com/Farchairul/portfolio/releases/download/v1.0.0-previews/Preview_TaktikBola.mp4',
  },
  {
    id: 'outdoor-equipment-rental-pos',
    title: 'Outdoor Equipment Rental POS',
    tagline: 'January 2026',
    category: 'Desktop Application | Java Developer',
    highlights: [
      'Developed a desktop rental management system for outdoor equipment businesses.',
      'Implemented rental transactions, equipment management, returns, and reporting.',
      'Applied a 3-layer architecture using Spring, Hibernate, and MySQL.',
    ],
    tags: ['Java 17', 'Spring Framework', 'Hibernate', 'MySQL', 'Java Swing', 'Maven'],
    githubUrl: 'https://github.com/Farchairul/sewaalatoutdoor',
  },
]

export const certificates: Certificate[] = [
  {
    badge: { label: 'Data Science', styleClass: 'cert-badge-yellow' },
    year: '2026',
    date: 'June 06, 2026',
    title: 'Data Science Course (Case 2)',
    issuer: 'Universitas Gunadarma',
    certNo: 'NO. 079318',
    description: 'Advanced Data Science Case 2 training covering data collection, data exploration, cleansing, validation, feature construction, data labeling, machine learning modeling, evaluation, and model deployment to production.',
    competencies: [
      'Data Collection, Understanding & Selection (2nd Case)',
      'Data Cleansing, Validation & Construction (2nd Case)',
      'Data Labeling & Machine Learning Modeling (2nd Case)',
      'Evaluation of Modeling & Deployment Planning & Model',
    ],
    image: '/certificates/ug-data-science-case2.png',
    page2Image: '/certificates/ug-data-science-case2-page2.png',
    pdfUrl: '/certificates/ug-data-science-case2.pdf',
  },
  {
    badge: { label: 'Data Science', styleClass: 'cert-badge-blue' },
    year: '2025',
    date: 'September 27, 2025',
    title: 'Data Science Course (Case 1)',
    issuer: 'Universitas Gunadarma',
    certNo: 'NO. 136371',
    description: 'Fundamental Data Science Case 1 training covering case study data collection, data exploration and cleaning, validation, feature engineering, labeling, machine learning modeling, and model evaluation.',
    competencies: [
      'Data Collection & Understanding (1st Case)',
      'Data Selection, Cleansing & Validation (1st Case)',
      'Data Construction & Data Labeling (1st Case)',
      'Machine Learning Modeling & Evaluation (1st Case)',
    ],
    image: '/certificates/ug-data-science-case1.png',
    page2Image: '/certificates/ug-data-science-case1-page2.png',
    pdfUrl: '/certificates/ug-data-science-case1.pdf',
  },
  {
    badge: { label: 'Udemy Certified', styleClass: 'cert-badge-yellow' },
    year: '2025',
    date: 'September 15, 2025',
    title: 'MS Excel Automation | Excel Data Analysis with Python',
    issuer: 'Udemy',
    certNo: 'UC-9895579a-9b11-42cb-b961-6040c8c606d6',
    description: 'Competency certification in Microsoft Excel automation and in-depth data analysis using Python, spreadsheet manipulation, analytical data visualization, and business workflow automation.',
    competencies: [
      'Excel Automation with Python Scripts',
      'Data Analysis & Cleaning in Python',
      'Automated Spreadsheet Manipulation',
      'Reporting Workflow & Data Analytics Pipelines',
    ],
    image: '/certificates/udemy-excel-python.png',
    pdfUrl: '/certificates/udemy-excel-python.pdf',
  },
  {
    badge: { label: 'Oracle Intermediate', styleClass: 'cert-badge-yellow' },
    year: '2025',
    date: 'August 18, 2025',
    title: 'Oracle for Intermediate Level',
    issuer: 'Universitas Gunadarma',
    certNo: 'NO. 128846',
    description: 'Intermediate Oracle training covering table creation and management, constraint handling, views, sub-queries, explicit cursors, and exception handling.',
    competencies: [
      'Create and Manage Table',
      'Constraint Handling & Create View',
      'Other Database Object & Sub Query',
      'Writing Explicit Cursors & Handling Exception',
    ],
    image: '/certificates/ug-oracle-intermediate.png',
    page2Image: '/certificates/ug-oracle-intermediate-page2.png',
    pdfUrl: '/certificates/ug-oracle-intermediate.pdf',
  },
  {
    badge: { label: 'Oracle Beginner', styleClass: 'cert-badge-blue' },
    year: '2024',
    date: 'August 19, 2024',
    title: 'Oracle for Beginners',
    issuer: 'Universitas Gunadarma',
    certNo: 'NO. 949594',
    description: 'Beginner Oracle training covering Oracle 11g installation, database design, user creation, single-row functions, and basic PL/SQL programming.',
    competencies: [
      'Oracle 11g Installation & Database Creation',
      'User Creation & Single-Row Functions',
      'Introduction to PL/SQL & Variable Declaration',
      'Statement Creation & Server Interaction',
    ],
    image: '/certificates/ug-oracle-beginner.png',
    page2Image: '/certificates/ug-oracle-beginner-page2.png',
    pdfUrl: '/certificates/ug-oracle-beginner.pdf',
  },
  {
    badge: { label: 'SQL Server', styleClass: 'cert-badge-blue' },
    year: '2024',
    date: 'February 19, 2024',
    title: 'SQL Server for Beginners',
    issuer: 'Universitas Gunadarma',
    certNo: 'NO. 426209',
    description: 'Microsoft SQL Server database administration and management training covering table creation, security & user roles, SQL functions, table joins, and control structures.',
    competencies: [
      'Administration System & Management Database SQL Server',
      'Manage Table & SQL Server Security & Role',
      'SQL Functions & Joining Tables',
      'SQL Server 2008 Programming & Control Structures',
    ],
    image: '/certificates/ug-sql-server-beginner.png',
    page2Image: '/certificates/ug-sql-server-beginner-page2.png',
    pdfUrl: '/certificates/ug-sql-server-beginner.pdf',
  },
  {
    badge: { label: 'Web Programming', styleClass: 'cert-badge-yellow' },
    year: '2024',
    date: 'February 19, 2024',
    title: 'Fundamentals of Web Programming',
    issuer: 'Universitas Gunadarma',
    certNo: 'NO. 143411',
    description: 'Fundamental Web Programming training covering introduction to web development, Go programming, control structures, J2EE servlets, JSP, ASP.NET C#, and server controls.',
    competencies: [
      'Introduction to Web Programming & Go Programming',
      'Control Structures in Go & Introduction to J2EE Servlets',
      'Java Server Pages (JSP) & Web-Based Applications',
      '.NET Framework, C#, and ASP.NET Server Controls',
    ],
    image: '/certificates/ug-fundamental-web-programming.png',
    page2Image: '/certificates/ug-fundamental-web-programming-page2.png',
    pdfUrl: '/certificates/ug-fundamental-web-programming.pdf',
  },
  {
    badge: { label: 'Fundamental DBMS', styleClass: 'cert-badge-blue' },
    year: '2023',
    date: 'February 20, 2023',
    title: 'Fundamentals of Database Management Systems',
    issuer: 'Universitas Gunadarma',
    certNo: 'NO. 182079',
    description: 'Fundamental DBMS training covering relational database concepts, DDL & DML in MySQL, SQL Server, and data manipulation syntax in Oracle.',
    competencies: [
      'Relational Database Concepts & SELECT Queries',
      'Data Definition Language (DDL) in MySQL',
      'Data Manipulation Language (DML) in MySQL',
      'DDL & DML in SQL Server and Oracle',
    ],
    image: '/certificates/ug-fundamental-dbms.png',
    page2Image: '/certificates/ug-fundamental-dbms-page2.png',
    pdfUrl: '/certificates/ug-fundamental-dbms.pdf',
  },
]
